"""BLAXCY entry point.

Phase 0 exposes the environment-truth commands the rest of the system is built
on. Nothing here injects input, opens a GUI, or contacts the Brain; it reports
what the machine can actually do.

Usage:
    python main.py probe     # functional capability report (default)
    python main.py session   # detected session/environment facts
    python main.py config    # resolved configuration and its source path
    python main.py keys      # Brain API key status (keyring only)
    python main.py keys set-gemini   # store the key, read from a hidden prompt
    python main.py status    # the assembled Body's live state (starts every component)
    python main.py run TASK  # run one task through the Brain and the real desktop

``status`` and ``run`` are the two commands that construct the whole Body
(core/application.py). ``status`` performs one real observation and injects no
input; ``run`` needs a stored Brain key and, headlessly, refuses any action that
requires a human confirmation rather than assuming one (sections 54, 56, 71).

``gui`` (section 71) is the same Body with a window over it. Qt is imported only
inside that command, so every other command works without a Qt binding installed.

``gui`` and ``run`` — the two commands that *own* the desktop — take the section 72
single-instance lock first, so a second Body is refused rather than silently
competing for the same mouse and keyboard. The read-only commands deliberately do
not: they inject nothing, so running one beside a live Body is safe and useful.
"""

from __future__ import annotations

import argparse
import getpass
import json
import sys
from pathlib import Path

from config.settings import Settings, effective_settings_path, load_settings
from core.application import BlaxcyApplication
from core.capability_probe import probe_all
from core.logging_setup import configure_logging
from core.session_detector import SessionInfo, detect_session
from core.single_instance import InstanceLock
from schemas.capability import CapabilityReport
from schemas.enums import CapabilityStatus, ErrorCode
from schemas.errors import BlaxcyError
from security.keyring_manager import ApiKeyManager


def _print_session(session: SessionInfo) -> None:
    """Render session facts as a compact key/value block."""
    print(f"session type      : {session.session_type.value}")
    print(f"DISPLAY           : {session.display or '(unset)'}")
    print(f"WAYLAND_DISPLAY   : {session.wayland_display or '(unset)'}")
    print(f"XDG_SESSION_TYPE  : {session.xdg_session_type or '(unset)'}")
    print(f"desktop           : {session.desktop_environment or session.session_desktop or '(unset)'}")
    print(f"os                : {session.os_name} {session.os_version}")
    print(f"python            : {session.python_version}")
    print(f"portal available  : {_fmt_optional_bool(session.portal_available)}")
    print(f"AT-SPI bus        : {_fmt_optional_bool(session.atspi_bus_available)}")
    for note in session.notes:
        print(f"note              : {note}")


def _fmt_optional_bool(value: bool | None) -> str:
    """Render a tri-state boolean honestly (unknown is not False)."""
    if value is None:
        return "UNKNOWN"
    return "yes" if value else "no"


def _print_report(report: CapabilityReport) -> None:
    """Render the capability report as an aligned table plus reasons."""
    print(f"session type: {report.session_type}")
    print()
    width = max(len(c.name.value) for c in report.capabilities)
    for cap in report.capabilities:
        latency = f"{cap.latency_ms:.1f} ms" if cap.latency_ms is not None else "-"
        backend = cap.backend or "-"
        print(f"{cap.name.value:<{width}}  {cap.status.value:<11} {backend:<14} {latency}")
        if cap.reason:
            print(f"{'':<{width}}  reason: {cap.reason}")
        if cap.fix_hint:
            print(f"{'':<{width}}  fix:    {cap.fix_hint}")
    print()
    available = len(report.by_status(CapabilityStatus.AVAILABLE))
    degraded = len(report.by_status(CapabilityStatus.DEGRADED))
    unavailable = len(report.by_status(CapabilityStatus.UNAVAILABLE))
    print(f"{pending_summary(available, degraded, unavailable)}")


def pending_summary(available: int, degraded: int, unavailable: int) -> str:
    """One-line tally used by the probe report footer."""
    return f"AVAILABLE: {available}   DEGRADED: {degraded}   UNAVAILABLE: {unavailable}"


def _write_report(report: CapabilityReport, session: SessionInfo, settings: Settings) -> Path:
    """Write the human-readable environment report to docs/environment_report.md."""
    target = Path(__file__).parent / "docs" / "environment_report.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# BLAXCY — Environment Report",
        "",
        "> Generated by `python main.py probe`. Read-only observation; no input injected.",
        "",
        "## Session",
        "",
        f"- Session type: `{session.session_type.value}`",
        f"- DISPLAY: `{session.display or '(unset)'}`",
        f"- WAYLAND_DISPLAY: `{session.wayland_display or '(unset)'}`",
        f"- XDG_SESSION_TYPE: `{session.xdg_session_type or '(unset)'}`",
        f"- Desktop: `{session.desktop_environment or session.session_desktop or '(unset)'}`",
        f"- OS: `{session.os_name} {session.os_version}`",
        f"- Python: `{session.python_version}`",
        f"- Portal available: {_fmt_optional_bool(session.portal_available)}",
        f"- AT-SPI bus available: {_fmt_optional_bool(session.atspi_bus_available)}",
        "",
        "## Capabilities",
        "",
        "| Capability | Status | Backend | Latency (ms) | Reason |",
        "|---|---|---|---|---|",
    ]
    for cap in report.capabilities:
        latency = f"{cap.latency_ms:.3f}" if cap.latency_ms is not None else "-"
        reason = (cap.reason or "").replace("|", "\\|")
        lines.append(
            f"| {cap.name.value} | {cap.status.value} | {cap.backend or '-'} | {latency} | {reason} |"
        )
    lines += [
        "",
        "## Configuration",
        "",
        f"- Effective config path: `{effective_settings_path()}`",
        f"- Policy mode: `{settings.safety.mode.value}`",
        f"- Resolver cache enabled: `{settings.resolver_cache.enabled}`",
        f"- Sequence execution enabled: `{settings.sequence.enabled}`",
        "",
        "## Notes",
        "",
    ]
    lines += [f"- {note}" for note in session.notes] or ["- none"]
    lines.append("")
    target.write_text("\n".join(lines), encoding="utf-8")
    return target


def _cmd_probe(args: argparse.Namespace) -> int:
    """Run the capability probe and print (or persist) the report."""
    settings = load_settings(Path(args.config) if args.config else None)
    session = detect_session()
    report = probe_all(settings, session)
    if args.json:
        print(json.dumps(report.to_dict(), indent=2))
    else:
        _print_report(report)
    if args.write_report:
        path = _write_report(report, session, settings)
        print(f"\nwrote {path}")
    return 0


def _cmd_session(args: argparse.Namespace) -> int:
    """Print detected session/environment facts."""
    session = detect_session()
    if args.json:
        print(json.dumps(session.model_dump(mode="json"), indent=2))
    else:
        _print_session(session)
    return 0


def _cmd_config(args: argparse.Namespace) -> int:
    """Print the resolved configuration and where it came from."""
    settings = load_settings(Path(args.config) if args.config else None)
    print(f"effective config: {effective_settings_path(Path(args.config) if args.config else None)}")
    print(json.dumps(settings.model_dump(mode="json"), indent=2))
    return 0


def _cmd_keys(args: argparse.Namespace) -> int:
    """Manage the Brain credential in the OS keyring (section 69).

    The key is never accepted as an argument: it is read from a hidden prompt, so
    it cannot end up in the shell history or the process table.
    """
    manager = ApiKeyManager()
    action = getattr(args, "keys_action", "status")

    if action == "status":
        print(json.dumps(manager.status(), indent=2))
        return 0

    if action == "clear-gemini":
        removed = manager.clear_gemini_key()
        print(
            "removed the stored Gemini API key"
            if removed
            else "no Gemini API key was stored"
        )
        return 0

    key = getpass.getpass("Gemini API key (hidden; never passed as an argument): ").strip()
    if not key:
        print("error [INTERNAL_ERROR]: refusing to store an empty key", file=sys.stderr)
        return 2
    manager.set_gemini_key(key)
    print(
        "stored the Gemini API key in the OS keyring "
        f"(service={manager.service!r}); it is not written to config, logs or argv"
    )
    return 0


def _cmd_status(args: argparse.Namespace) -> int:
    """Report the assembled Body's real state, starting every component."""
    settings = load_settings(Path(args.config) if args.config else None)
    # No watchdog for a read-only report: it holds no input, so there is nothing
    # for a crash guard to release, and a status command should leave no
    # heartbeat file behind.
    app = BlaxcyApplication(settings, with_watchdog=False)
    app.start()
    try:
        app.perceive()  # one real observation, so the report is about this desktop
        report = app.status()
        if args.json:
            print(json.dumps(report, indent=2))
        else:
            _print_status(report)
    finally:
        app.shutdown()
    return 0


def _print_status(report: dict[str, object]) -> None:
    """Render the status snapshot as a compact block."""
    startup = report["startup"]
    state = report["state"]
    caps = report["capabilities"]
    assert isinstance(startup, dict) and isinstance(state, dict)
    print(f"session           : {report['session_type']}")
    print(f"mode              : {report['mode']}")
    print(f"started           : {report['started']}")
    print(f"input backend     : {startup['input_backend'] or '(none available)'}")
    print(f"accessibility     : {startup['accessibility']}")
    print(f"clipboard         : {startup['clipboard']}")
    print(f"window manager    : {startup['window_manager']}")
    print(f"brain             : {startup['brain'] or '(not connected)'}")
    print(f"sequence enabled  : {startup['sequence_enabled']}")
    print(f"resolver cache    : {startup['resolver_cache_enabled']}")
    print(f"state frame id    : {state['frame_id']}")
    print(f"state age (ms)    : {state['age_ms']}")
    print(f"elements observed : {state['element_count']}")
    print(f"active app        : {state['active_app']}")
    if isinstance(caps, dict):
        print(f"capabilities      : {pending_summary(caps['AVAILABLE'], caps['DEGRADED'], caps['UNAVAILABLE'])}")
    notes = startup["notes"]
    assert isinstance(notes, list)
    for note in notes:
        print(f"note              : {note}")


def _cmd_run(args: argparse.Namespace) -> int:
    """Run one task through the Brain and the real desktop (section 67).

    There is deliberately no ``--yes``/``--confirm`` flag: a confirmation is a
    human decision shown with the action, the target and any literal terminal
    text, and a flag that answers it in advance would be exactly the bypass
    sections 54 and 71 forbid. Headless, an action that needs one is refused.
    """
    lock = _acquire_instance_lock(getattr(args, "lock_path", None))
    if lock is None:
        return 2
    try:
        settings = load_settings(Path(args.config) if args.config else None)
        app = BlaxcyApplication(settings)
        app.start()
        try:
            # Seed the perception cache before the Brain speaks: the first
            # ``get_screen_state`` must observe a real frame, not fail
            # CAPTURE_FAILED because nothing has been observed yet.
            app.perceive()
            result = app.run_task(args.task)
            print(json.dumps(result.to_dict(), indent=2))
            return 2 if result.halted else 0
        finally:
            app.shutdown()
    finally:
        lock.release()


def _acquire_instance_lock(lock_path: str | None = None) -> InstanceLock | None:
    """Take the section 72 single-instance lock, or report why it is refused.

    The refusal is printed without a bracketed error code on purpose. Section 77's
    taxonomy describes *action* failures, and its exact list is pinned by
    ``tests/unit/test_error_taxonomy.py``; a refused second launch never reaches an
    action, so labelling it with an action code would misdescribe it.

    The lock path is an explicit flag and never a configuration value: a user
    config must not be able to switch off the guarantee that a second Body is
    refused (section 4 rule 25).
    """
    lock = InstanceLock(
        Path(lock_path).expanduser() if lock_path else None,
        command=" ".join(sys.argv[:3]),
    )
    if lock.acquire():
        return lock
    print(f"error: {lock.refusal_message()}", file=sys.stderr)
    return None


def _cmd_gui(args: argparse.Namespace) -> int:
    """Open the GUI over a real Body (section 71).

    The Qt import is deliberately local: ``probe``/``session``/``config``/``keys``
    must work on a machine with no Qt binding, and a missing PySide6 must be an
    honest error from *this* command rather than an ImportError at startup.
    """
    argv: list[str] = []
    if args.config:
        argv += ["--config", args.config]
    if args.offscreen:
        argv.append("--offscreen")
    try:
        from gui.app import run as run_gui
    except ImportError as exc:
        print(
            f"error [{ErrorCode.BACKEND_UNAVAILABLE.value}]: the GUI needs PySide6, "
            f"which is not importable: {exc!r}",
            file=sys.stderr,
        )
        return 2
    lock = _acquire_instance_lock(getattr(args, "lock_path", None))
    if lock is None:
        return 2
    try:
        return run_gui(argv)
    finally:
        lock.release()


def _build_parser() -> argparse.ArgumentParser:
    """Construct the CLI parser."""
    parser = argparse.ArgumentParser(
        prog="blaxcy",
        description="BLAXCY — Linux-native AI computer-control BODY.",
    )
    parser.add_argument(
        "--config",
        metavar="PATH",
        default=None,
        help="explicit TOML config path (defaults to ~/.config/blaxcy/config.toml)",
    )
    parser.add_argument(
        "--lock-path",
        metavar="PATH",
        default=None,
        help="section 72 single-instance lock file (used by gui/run; defaults to "
        "$XDG_RUNTIME_DIR/blaxcy/instance.lock)",
    )
    sub = parser.add_subparsers(dest="command")

    probe = sub.add_parser("probe", help="run the functional capability report (default)")
    probe.add_argument("--json", action="store_true", help="emit JSON instead of a table")
    probe.add_argument(
        "--write-report",
        action="store_true",
        help="also write docs/environment_report.md",
    )
    probe.set_defaults(func=_cmd_probe)

    session = sub.add_parser("session", help="show detected session/environment facts")
    session.add_argument("--json", action="store_true", help="emit JSON")
    session.set_defaults(func=_cmd_session)

    config = sub.add_parser("config", help="show the resolved configuration")
    config.set_defaults(func=_cmd_config)

    keys = sub.add_parser("keys", help="manage the Brain API key in the OS keyring")
    keys.add_argument(
        "keys_action",
        nargs="?",
        default="status",
        choices=("status", "set-gemini", "clear-gemini"),
        help="what to do with the stored key (default: report status)",
    )
    keys.set_defaults(func=_cmd_keys)

    status = sub.add_parser(
        "status", help="start every component and report the assembled Body's state"
    )
    status.add_argument("--json", action="store_true", help="emit JSON")
    status.set_defaults(func=_cmd_status)

    gui = sub.add_parser(
        "gui", help="open the section 71 window over the assembled Body"
    )
    gui.add_argument(
        "--offscreen",
        action="store_true",
        help="force the Qt offscreen platform (no display server needed)",
    )
    gui.set_defaults(func=_cmd_gui)

    run = sub.add_parser("run", help="run one task through the Brain and the real desktop")
    run.add_argument("task", help="the task text handed to the Brain")
    run.set_defaults(func=_cmd_run)

    return parser


def _configure_logging(args: argparse.Namespace) -> Path | None:
    """Install structured file logging (section 70) before the command runs.

    Best effort on purpose: a config the loader refuses is the *command's* error
    to report with its taxonomy code (see ``_cmd_config``), not a reason for
    logging setup to raise first and mask it. Returns the log path when one was
    established, so the caller can mention it.
    """
    try:
        settings = load_settings(Path(args.config) if args.config else None)
    except BlaxcyError:
        return None
    return configure_logging(settings)


def main(argv: list[str] | None = None) -> int:
    """CLI entry point. Returns a process exit code."""
    parser = _build_parser()
    args = parser.parse_args(argv)
    if getattr(args, "func", None) is None:
        # Default action: probe, with the standard table output.
        args = parser.parse_args(["probe", *(argv if argv is not None else [])])
    try:
        _configure_logging(args)
        return int(args.func(args))
    except BlaxcyError as exc:
        print(f"error [{exc.code.value}]: {exc.message}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
