"""BLAXCY entry point.

Phase 0 exposes the environment-truth commands the rest of the system is built
on. Nothing here injects input, opens a GUI, or contacts the Brain; it reports
what the machine can actually do.

Usage:
    python main.py probe     # functional capability report (default)
    python main.py session   # detected session/environment facts
    python main.py config    # resolved configuration and its source path
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from config.settings import Settings, effective_settings_path, load_settings
from core.capability_probe import probe_all
from core.session_detector import SessionInfo, detect_session
from schemas.capability import CapabilityReport
from schemas.enums import CapabilityStatus
from schemas.errors import BlaxcyError


def _print_session(session: SessionInfo) -> None:
    """Render session facts as a compact key/value block."""
    print(f"session type      : {session.session_type.value}")
    print(f"DISPLAY           : {session.display or '(unset)'}")
    print(f"WAYLAND_DISPLAY   : {session.wayland_display or '(unset)'}")
    print(f"XDG_SESSION_TYPE  : {session.xdg_session_type or '(unset)'}")
    print(f"desktop           : {session.desktop_environment or session.session_desktop or '(unset)'}")
    print(f"os                : {session.os_name} {session.os_version}")
    print(f"python            : {session.python_version}")
    print(f"portal available  : {_fmt_optional_bool(session.portal_available)}")
    print(f"AT-SPI bus        : {_fmt_optional_bool(session.atspi_bus_available)}")
    for note in session.notes:
        print(f"note              : {note}")


def _fmt_optional_bool(value: bool | None) -> str:
    """Render a tri-state boolean honestly (unknown is not False)."""
    if value is None:
        return "UNKNOWN"
    return "yes" if value else "no"


def _print_report(report: CapabilityReport) -> None:
    """Render the capability report as an aligned table plus reasons."""
    print(f"session type: {report.session_type}")
    print()
    width = max(len(c.name.value) for c in report.capabilities)
    for cap in report.capabilities:
        latency = f"{cap.latency_ms:.1f} ms" if cap.latency_ms is not None else "-"
        backend = cap.backend or "-"
        print(f"{cap.name.value:<{width}}  {cap.status.value:<11} {backend:<14} {latency}")
        if cap.reason:
            print(f"{'':<{width}}  reason: {cap.reason}")
        if cap.fix_hint:
            print(f"{'':<{width}}  fix:    {cap.fix_hint}")
    print()
    available = len(report.by_status(CapabilityStatus.AVAILABLE))
    degraded = len(report.by_status(CapabilityStatus.DEGRADED))
    unavailable = len(report.by_status(CapabilityStatus.UNAVAILABLE))
    print(f"{pending_summary(available, degraded, unavailable)}")


def pending_summary(available: int, degraded: int, unavailable: int) -> str:
    """One-line tally used by the probe report footer."""
    return f"AVAILABLE: {available}   DEGRADED: {degraded}   UNAVAILABLE: {unavailable}"


def _write_report(report: CapabilityReport, session: SessionInfo, settings: Settings) -> Path:
    """Write the human-readable environment report to docs/environment_report.md."""
    target = Path(__file__).parent / "docs" / "environment_report.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# BLAXCY — Environment Report",
        "",
        "> Generated by `python main.py probe`. Read-only observation; no input injected.",
        "",
        "## Session",
        "",
        f"- Session type: `{session.session_type.value}`",
        f"- DISPLAY: `{session.display or '(unset)'}`",
        f"- WAYLAND_DISPLAY: `{session.wayland_display or '(unset)'}`",
        f"- XDG_SESSION_TYPE: `{session.xdg_session_type or '(unset)'}`",
        f"- Desktop: `{session.desktop_environment or session.session_desktop or '(unset)'}`",
        f"- OS: `{session.os_name} {session.os_version}`",
        f"- Python: `{session.python_version}`",
        f"- Portal available: {_fmt_optional_bool(session.portal_available)}",
        f"- AT-SPI bus available: {_fmt_optional_bool(session.atspi_bus_available)}",
        "",
        "## Capabilities",
        "",
        "| Capability | Status | Backend | Latency (ms) | Reason |",
        "|---|---|---|---|---|",
    ]
    for cap in report.capabilities:
        latency = f"{cap.latency_ms:.3f}" if cap.latency_ms is not None else "-"
        reason = (cap.reason or "").replace("|", "\\|")
        lines.append(
            f"| {cap.name.value} | {cap.status.value} | {cap.backend or '-'} | {latency} | {reason} |"
        )
    lines += [
        "",
        "## Configuration",
        "",
        f"- Effective config path: `{effective_settings_path()}`",
        f"- Policy mode: `{settings.safety.mode.value}`",
        f"- Resolver cache enabled: `{settings.resolver_cache.enabled}`",
        f"- Sequence execution enabled: `{settings.sequence.enabled}`",
        "",
        "## Notes",
        "",
    ]
    lines += [f"- {note}" for note in session.notes] or ["- none"]
    lines.append("")
    target.write_text("\n".join(lines), encoding="utf-8")
    return target


def _cmd_probe(args: argparse.Namespace) -> int:
    """Run the capability probe and print (or persist) the report."""
    settings = load_settings(Path(args.config) if args.config else None)
    session = detect_session()
    report = probe_all(settings, session)
    if args.json:
        print(json.dumps(report.to_dict(), indent=2))
    else:
        _print_report(report)
    if args.write_report:
        path = _write_report(report, session, settings)
        print(f"\nwrote {path}")
    return 0


def _cmd_session(args: argparse.Namespace) -> int:
    """Print detected session/environment facts."""
    session = detect_session()
    if args.json:
        print(json.dumps(session.model_dump(mode="json"), indent=2))
    else:
        _print_session(session)
    return 0


def _cmd_config(args: argparse.Namespace) -> int:
    """Print the resolved configuration and where it came from."""
    settings = load_settings(Path(args.config) if args.config else None)
    print(f"effective config: {effective_settings_path(Path(args.config) if args.config else None)}")
    print(json.dumps(settings.model_dump(mode="json"), indent=2))
    return 0


def _build_parser() -> argparse.ArgumentParser:
    """Construct the CLI parser."""
    parser = argparse.ArgumentParser(
        prog="blaxcy",
        description="BLAXCY — Linux-native AI computer-control BODY (Phase 0).",
    )
    parser.add_argument(
        "--config",
        metavar="PATH",
        default=None,
        help="explicit TOML config path (defaults to ~/.config/blaxcy/config.toml)",
    )
    sub = parser.add_subparsers(dest="command")

    probe = sub.add_parser("probe", help="run the functional capability report (default)")
    probe.add_argument("--json", action="store_true", help="emit JSON instead of a table")
    probe.add_argument(
        "--write-report",
        action="store_true",
        help="also write docs/environment_report.md",
    )
    probe.set_defaults(func=_cmd_probe)

    session = sub.add_parser("session", help="show detected session/environment facts")
    session.add_argument("--json", action="store_true", help="emit JSON")
    session.set_defaults(func=_cmd_session)

    config = sub.add_parser("config", help="show the resolved configuration")
    config.set_defaults(func=_cmd_config)

    return parser


def main(argv: list[str] | None = None) -> int:
    """CLI entry point. Returns a process exit code."""
    parser = _build_parser()
    args = parser.parse_args(argv)
    if getattr(args, "func", None) is None:
        # Default action: probe, with the standard table output.
        args = parser.parse_args(["probe", *(argv if argv is not None else [])])
    try:
        return int(args.func(args))
    except BlaxcyError as exc:
        print(f"error [{exc.code.value}]: {exc.message}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
